name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your Python version if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-light.txt

    - name: Build Jupyter Book
      run: jupyter-book build VariationalLaplaceForDummies/

    - name: Deploy to GitHub Pages
      run: ghp-import -n -p -f VariationalLaplaceForDummies/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
